### PR TITLE
Use same async sleep function throughout source code

### PR DESCRIPTION
**Pull request by Dastan-glitch**
Issue #46

### CODE REVIEW

**Comment by parazyd** [comment]
@Dastan-glitch Hey can you fix the conflict please?

**Comment by Dastan-glitch** [comment]
Sorry I took to long to resolve it
I just changed the name why the format check wasn't successful?

**Comment by parazyd** [comment]
I recommend running `cargo +nightly fmt` before committing. You could also set up a git hook to remind you to do so, like here: https://darkrenaissance.github.io/darkfi/development.html

**Comment by Dastan-glitch** [comment]
Yeah, that's what i did in the first commit, after that just renaming a file would require `cargo +nightly fmt` again?

**Comment by Dastan-glitch** [comment]
Ah!, alphabet order. -_-

**Comment by parazyd** [comment]
> Yeah, that's what i did in the first commit, after that just renaming a file would require `cargo +nightly fmt` again?

Yeah, since the module is under a different name, so the import order changes.

**Pull request merged**
