### PR TITLE
stdsimd-removed-use-nightly-202402 in rust-toolchain.toml

### PR DESCRIPTION
**Pull request by spital**
For latest build ARM/x64

can be used via git apply or patch -p1 from https://github.com/darkrenaissance/darkfi/pull/<<PATCH_NUMBER>>.patch

### CODE REVIEW

**Comment by aggstam** [comment]
As per [living-on-the-cutting-edge](https://github.com/darkrenaissance/darkfi?tab=readme-ov-file#living-on-the-cutting-edge), we don't need to make this change, its better to wait for dependencies to fix their versions.
In case its required in some builder, etc, you can follow that steps in its config, like in the gh ci pipelines  1eaf5fae35bac1ab793a06ed57a1a98000544757

**Comment by spital** [comment]
Thank you, I'd rather not rely on Microsoft's Github workflows, also these PRs are useful to build dockers:

git checkout master
git pull
git checkout 9f1649ef0
curl -L https://github.com/darkrenaissance/darkfi/pull/254.patch | git apply -v -
curl -L https://github.com/darkrenaissance/darkfi/pull/253.patch | git apply -v -
curl -L https://github.com/darkrenaissance/darkfi/pull/238.patch | git apply -v -
curl -L https://github.com/darkrenaissance/darkfi/pull/215.patch | git apply -v -

TAG=9f1649ef0__2024-02-17
SHM=196m
ARCH=$(uname -m)
RUST=nightly-2024-02-04

BINS="minerd darkfi-mmproxy  darkfid  darkirc  drk  genev  genevd  lilith  swapd  taud  vanityaddr  zkas"

DOCKER_BUILDKIT=0  docker build . --no-cache --pull --shm-size=$SHM --build-arg RUST_VER=${RUST} --build-arg BINS="$BINS" -t darkfi:${ARCH}_fedora_$TAG -f $DFDIR/Dockerfile.fedora

Maybe I'll try to ping on ircd ;)

**Comment by aggstam** [comment]
Hey @spital,
I never said to rely on Microsoft Github workflows, I pointed at them as an example on how to modify your docker building scripts...

**Comment by dark-john** [comment]
This is fantastic!  I've been using Github for years but was not aware of this little trick.  Nice.

https://github.com/darkrenaissance/darkfi/pull/254.patch

Looks like Codeberg supports it too.

**Pull request closed without merging**
