### PR TITLE
`bin/fud/README.md`: Minor typo fixes

### PR DESCRIPTION
**Pull request by leopardracer**
This pull request contains changes to improve clarity, correctness and structure.

**Description correction:**
Corrected `Additionaly` to `Additionally`.
Corrected `seedd_config.toml` to `seed_config.toml` x2.

Please review the changes and let me know if any additional changes are needed.

### CODE REVIEW

**Comment by aggstam** [comment]
Please follow contribution guidelines as per: https://darkrenaissance.github.io/darkfi/dev/dev.html#making-life-easy-for-others

Commit message should look like: `bin/fud/README.md: Minor typo fixes`

**Comment by leopardracer** [comment]
> Please follow contribution guidelines as per: https://darkrenaissance.github.io/darkfi/dev/dev.html#making-life-easy-for-others
> 
> Commit message should look like: `bin/fud/README.md: Minor typo fixes`

Corrected

**Comment by aggstam** [comment]
No it's not, commit message is still `Update README.md`

**Comment by leopardracer** [comment]
> No it's not, commit message is still `Update README.md`

Corrected

**Comment by aggstam** [comment]
Ok so for actual PR contents, `seedd_config.toml` is not a typo its an example file name.
Closing this PR as too minor.
For future references, micro commits like this will not get accepted.

**Pull request closed without merging**
